version: '3'

services:
  node:
    build: ./docker/node
    ports:
      - 8092:3000
    volumes:
      - ./docker/node/src:/micro-test
    tty: true
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.3.15-bionic
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 13309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
